In [1]:
# List

x = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

sum = 0
for i in x:
    sum += i
print(sum)

55


In [2]:
# Numpy array

import numpy as np
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(np.sum(x), np.mean(x), np.std(x))

55 5.5 2.8722813232690143


## Why it useful?

In [13]:
import time
sTime = time.time()
L = range(1000000)
b = [i**2 for i in L]
eTime = time.time()
print(eTime - sTime)

0.40494585037231445


In [14]:
sTime = time.time()
c = np.arange(1000000)
d = c**2
eTime = time.time()
print(eTime - sTime)

0.004026174545288086


## Random number

* Manual method: coin flipping, dice rolling, card shuffling and roulette wheels
We can get “truly” random numbers but these methods were too slow for general use.
* Method of using computer <br>
1) Mid-Square method <br>
    For example, if we are generating 4-digit numbers and arrive at 5232,

    5232\*\*2 = 27,373,824, we get 3738, <br>
    3738\*\*2 = 13,972,644, we get 9726, <br>
    9726\*\*2 = 94,595,080, we get 5950, <br>

    and so on. This numbers are not “truly” random, we called this “Pseudo-random” or “Quasi-Random”. <br>
    
    2) Multiplicative generator
   The second widely used generator is the multiplicative generator. <br>
   
   $$ \ X_i = a X_{i-1} \% \thinspace m, \thinspace m = 2 ^\beta, \, a = 2^{17} +3, \beta = 35  $$
   
   $$ X_0=YY+100*(MM-1+12*(DD-1+31*(HH+24* (Min+60 *SS)))) $$

In [2]:
import numpy as np
a = np.random.rand(4) # uniform in [0, 1]
a

array([0.96745649, 0.03535207, 0.21777958, 0.4332216 ])

In [8]:
# 난수 발생방법 전산통계 2주차 1 강의 참조

* Bin(n,p): the binomial distribution with parameters n and p is the discrete probability distribution of the number of successes in a sequence of n independent experiments, each asking a yes–no question, and each with its own boolean-valued outcome.

In [3]:
n, p = 4, 0.3
x = np.random.binomial(n,p,100)
x

array([0, 3, 1, 1, 0, 2, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 4,
       1, 0, 1, 0, 3, 2, 2, 1, 1, 0, 3, 1, 1, 1, 1, 3, 1, 1, 2, 0, 1, 3,
       2, 1, 0, 1, 0, 2, 2, 0, 1, 3, 1, 1, 0, 3, 1, 1, 2, 1, 2, 2, 1, 1,
       2, 2, 1, 1, 1, 2, 0, 3, 1, 0, 0, 0, 1, 2, 4, 0, 2, 0, 1, 0, 2, 2,
       1, 2, 2, 0, 0, 3, 1, 2, 1, 2, 3, 3])

In [4]:
np.mean(x)

1.26

*  the normal (or Gaussian or Gauss or Laplace–Gauss) distribution is a very common continuous probability distribution. Normal distributions are important in statistics and are often used in the natural and social sciences to represent real-valued random variables whose distributions are not known.

$$ f(x) = \frac{1}{\sqrt{2\pi \sigma^2}} exp\left(-\frac{(x-\mu)^2}{2 \sigma^2} \right) \, dx $$

In [5]:
x = np.random.normal(0, 1, 100)
x

array([ 0.0114946 , -0.68654302, -1.37211717, -0.09752818,  1.21570243,
        0.92032141, -1.49295893,  0.85341576, -0.88857322, -1.08192941,
        0.88707052,  0.7000338 , -0.57275312,  0.49752309, -0.25414574,
       -0.55320077,  0.93959992,  1.90796062, -1.24415265,  0.47343976,
        0.33001315, -0.13967814,  0.47488233,  1.85628182,  0.53490209,
        1.22132892, -1.42908598, -0.6112397 ,  1.26685394, -2.38916014,
        0.74527094,  0.7459177 ,  0.32526912, -1.01931518,  0.26279333,
       -0.47622402,  0.15409339, -0.60250196, -0.58191142,  1.55532166,
       -0.6151067 , -1.86555542, -0.44869845,  0.93368216, -0.01469633,
       -0.6112877 , -0.40850457,  1.08676735, -1.05879528, -0.42812982,
       -0.54941448, -1.40513286, -0.95442321,  1.83888547,  2.40700906,
        0.37691979,  0.15215117,  0.84234507,  1.23700333, -0.71752892,
       -1.23079628, -0.20403854,  0.02675056,  0.38429931,  1.43093198,
       -1.66899794, -0.14873011,  1.73047278,  0.13195909, -0.82

In [6]:
np.mean(x)

0.037873221457714434

In [7]:
np.std(x)

0.9821305024288673

## Basic Data types

In [9]:
a = np.array([1, 2, 3])
a.dtype

dtype('int32')

In [10]:
b = np.array([1.,2.,3.])
b.dtype

dtype('float64')

In [12]:
f = np.array(['abcdefg', 'b', 'c'])
f.dtype

dtype('<U7')

## Indexing & slicing

In [13]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
a[0], a[2], a[-1]

(0, 2, 9)

In [15]:
a[::-1] # Reverse order

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [16]:
a = np.diag(np.arange(3))
a

array([[0, 0, 0],
       [0, 1, 0],
       [0, 0, 2]])

In [20]:
a[2, 1] = 10
a[2]
a

array([[ 0,  0,  0],
       [ 0,  1,  0],
       [ 0, 10,  2]])

In [21]:
a[:2]

array([[0, 0, 0],
       [0, 1, 0]])

In [25]:
a[::2]

array([[ 0,  0,  0],
       [ 0, 10,  2]])

In [26]:
a[:,:2]

array([[ 0,  0],
       [ 0,  1],
       [ 0, 10]])

In [27]:
np.arange(0,51,10).shape

(6,)

In [28]:
np.arange(0,51,10)[:,np.newaxis]

array([[ 0],
       [10],
       [20],
       [30],
       [40],
       [50]])

In [29]:
np.arange(0,51,10).reshape(6,1)

array([[ 0],
       [10],
       [20],
       [30],
       [40],
       [50]])

In [30]:
a = np.arange(6) + np.arange(0,51,10).reshape(6,1)
a #이러한 연산도 가능하다

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [31]:
a[0,3:5]

array([3, 4])

In [32]:
a[4:,4:]

array([[44, 45],
       [54, 55]])

In [33]:
a[:,2]

array([ 2, 12, 22, 32, 42, 52])

In [34]:
a[2:]

array([[20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [35]:
a[2::2,::2]

array([[20, 22, 24],
       [40, 42, 44]])

## Prime number
* general algorithm <br>
  Exclude numbers divided by a smaller number while increasing the number from 2 to 100.

In [36]:
primeList = list(range(2,101))

for i in range(2,101):
    for j in range(2, i):
        if i% j == 0:
            primeList.remove(i)
            break
            
print(primeList)

[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97]


* another algorithm <br>
  The below numbers are not prime numbers.

    2 : 4, 6, 8, ... <br>
    3: 6, 9,12, ...<br>
    4: 8, 12, 16, ...<br>
   
   until 
    $\sqrt n $ 
    
    why $\sqrt n $ ?    if a * b = n, it satisfies min(a,b) <= sqrt(n).

In [37]:
is_prime = np.array(list(range(101)))
print(is_prime[4::2])

[  4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36  38
  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72  74
  76  78  80  82  84  86  88  90  92  94  96  98 100]


In [38]:
is_prime = np.array(list(range(101)))
N_max = int(np.sqrt(len(is_prime) - 1))

for j in range(2, N_max + 1):
    is_prime[2 * j::j] = 0
    
print(is_prime)

[ 0  1  2  3  0  5  0  7  0  0  0 11  0 13  0  0  0 17  0 19  0  0  0 23
  0  0  0  0  0 29  0 31  0  0  0  0  0 37  0  0  0 41  0 43  0  0  0 47
  0  0  0  0  0 53  0  0  0  0  0 59  0 61  0  0  0  0  0 67  0  0  0 71
  0 73  0  0  0  0  0 79  0  0  0 83  0  0  0  0  0 89  0  0  0  0  0  0
  0 97  0  0  0]


In [40]:
np.setdiff1d(is_prime,np.array([0,1])) # is_prime - [0,1]

array([ 2,  3,  5,  7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59,
       61, 67, 71, 73, 79, 83, 89, 97])

In [47]:
a = np.arange(22)
np.random.choice(a, 15, False) # 비복원 추출, sampling without replacement

array([ 6,  0, 19, 15, 21,  8, 18, 16, 17,  9, 11, 20,  4, 14,  1])

In [41]:
a = np.random.randint(0, 21, 15) # 복원 추출, sampling with replacement

In [42]:
a

array([ 0, 14, 14, 11,  8,  5, 19, 19,  3, 19, 19, 18,  7,  4, 20])

In [43]:
a % 3 == 0

array([ True, False, False, False, False, False, False, False,  True,
       False, False,  True, False, False, False])

In [44]:
a[a % 3 == 0]

array([ 0,  3, 18])

## Matrix Operation

In [48]:
a = np.array([1, 2, 3, 4])
a + 1

array([2, 3, 4, 5])

In [49]:
2 ** a

array([ 2,  4,  8, 16], dtype=int32)

In [50]:
b = np.ones(4) + 1
b

array([2., 2., 2., 2.])

In [51]:
a * b

array([2., 4., 6., 8.])

In [52]:
c = np.ones((3,3))
c

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [53]:
c.dot(c)

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])

In [65]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])
a == b

array([False,  True, False,  True])

In [66]:
a = np.array([1, 1, 0, 0])
b = np.array([1, 0, 1, 0])
np.logical_or(a, b)

array([ True,  True,  True, False])

In [67]:
np.logical_and(a, b)

array([ True, False, False, False])

In [68]:
np.logical_xor(a, b)

array([False,  True,  True, False])

In [59]:
a = np.array([1, 2, 3, 4])
np.log(a)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [61]:
a = np.triu(np.ones((3,3)),1)
a

array([[0., 1., 1.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [62]:
a.T

array([[0., 0., 0.],
       [1., 0., 0.],
       [1., 1., 0.]])

In [63]:
a += a.T
a

array([[0., 1., 1.],
       [1., 0., 1.],
       [1., 1., 0.]])

In [69]:
x = np.array([1, 2, 3, 4])
np.sum(x)

10

In [70]:
x.sum()

10

In [72]:
x = np.array([[1, 1], [2, 2]])
x

array([[1, 1],
       [2, 2]])

In [73]:
x .sum(axis = 0) # column sum

array([3, 3])

In [74]:
x.sum(axis = 1) # row sum

array([2, 4])

In [75]:
x.sum()

6

In [76]:
x = np.array([list(range(8))]).reshape(2,2,2)
x

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [77]:
x.sum(axis=0)

array([[ 4,  6],
       [ 8, 10]])

In [78]:
x.sum(axis=1)

array([[ 2,  4],
       [10, 12]])

In [79]:
x.sum(axis=2)

array([[ 1,  5],
       [ 9, 13]])

In [80]:
x = np.array([1, 3, 2])
x.argmax()

1

In [81]:
x.argmin()

0

In [86]:
x = np.array([1, 2, 3, 1])
y = np.array([[1, 2, 3], [5, 6, 1]])
print(y)
x.mean()

[[1 2 3]
 [5 6 1]]


1.75

In [83]:
np.median(x)

1.5

In [84]:
np.median(y, axis=0)

array([3., 4., 2.])

In [85]:
np.median(y, axis=1)

array([2., 5.])

In [88]:
print(x.std()) #분모가 n
print(x.std(ddof=1)) #분모가 n-1

0.82915619758885
0.9574271077563381


## Broadcasting
![broadcasting](https://drive.google.com/uc?id=1nnSRhOHeMHljnSBsL_A4838w8wVYsItL)

In [3]:
a = np.tile(np.arange(0, 40, 10), (3, 1)).T
a

array([[ 0,  0,  0],
       [10, 10, 10],
       [20, 20, 20],
       [30, 30, 30]])

In [4]:
b = np.array([0, 1, 2])
a + b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [5]:
a = np.ones((4,5))
a

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [6]:
a[0] = 2
a

array([[2., 2., 2., 2., 2.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### Array shape Manipulation

In [7]:
a = np.array([[1, 2, 3,],[4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
a.shape

(2, 3)

In [9]:
# Flatten
a = a.ravel()
print(a)

[1 2 3 4 5 6]


In [10]:
a.reshape(2,-1)

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
z = np.array([1, 2, 3]) # shape (3,) 
z.shape 

(3,)

In [12]:
z1 = z[:, np.newaxis] # add new axis

In [17]:
z1

array([[1],
       [2],
       [3]])

In [18]:
z1.shape

(3, 1)

In [14]:
z2 = z1[:,np.newaxis]

In [15]:
z2

array([[[1]],

       [[2]],

       [[3]]])

In [16]:
z2.shape

(3, 1, 1)

In [19]:
z1 = z[np.newaxis,:]
z1

array([[1, 2, 3]])

In [20]:
z1.shape

(1, 3)

### Array Sorting

In [21]:
a = np.array([[4, 3, 5], [1, 2, 1]])
b = np.sort(a)
b

array([[3, 4, 5],
       [1, 1, 2]])

In [22]:
a = np.array([4, 3, 1, 2])
j = np.argsort(a)
j

# 1 is the smallest, and the position is the 2.

array([2, 3, 1, 0], dtype=int64)

In [23]:
a[j]

array([1, 2, 3, 4])

### Data type

In [2]:
import numpy as np
np.array([1, 2, 3]) + 1.5

array([2.5, 3.5, 4.5])

In [3]:
a = np.array([1, 2, 3])
a.dtype

dtype('int32')

In [4]:
a[0] = 1.9
a

array([1, 2, 3])

In [5]:
a = np.array([1.7, 1.2, 1.6])
b = a.astype(int) # <-- truncates to integer
b

array([1, 1, 1])

In [6]:
np.iinfo(np.uint32).max, 2**32 - 1

(4294967295, 4294967295)

In [7]:
np.iinfo(np.int64).max, 2**63 - 1

(9223372036854775807, 9223372036854775807)

In [8]:
np.float32(1e-8) + np.float32(1) == 1

True

In [9]:
np.float64(1e-8) + np.float64(1) == 1

False

### Crude integral approximations (Monte-Carlo Integration)
$$ \int_0^1 \int_0^1 \int_0^1 (a^b-c)\ da\ db\ dc = ?$$
$$ The \ exact \ result \ is:\  ln \ 2 - \frac {1}{2} = 0.1931 ... $$
$$ E(X) = \int x \cdot f(x) \ dx \approx \frac {1}{n} \sum x_i , \ x_i \sim f(x) $$
$$ \int_0^1 \int_0^1 \int_0^1 (a^b-c)\ da\ db\ dc \approx
\frac {1}{n} \sum \left( {a_i}^{b_i} - c_i \right) , (a_i , b_i , c_i ) \sim U(0,1) $$

In [16]:
def f(a, b, c):
    return a**b - c

a = np.random.uniform(0,1,10000)
b = np.random.uniform(0,1,10000)
c = np.random.uniform(0,1,10000)

samples = f(a,b,c)
integral = samples.mean()
print ("Approximation:", integral)

Approximation: 0.19615503642287435
